<?php
/**
 * Created by PhpStorm.
 * User: ZQ
 * Date: 2019/3/4
 * Time: 9:51
 */

namespace backend\modules\api\controllers;


use backend\components\forms\Tools;
use backend\controllers\base\Base;
use kucha\ueditor\UEditorAction;
use yii\helpers\Json;
use yii\web\Response;
use Yii;
use yii\web\UploadedFile;

class ToolsController extends Base
{
    public function actions()
    {
        $actions = [
            'upload' => [
                'class' => UEditorAction::className(),
                'config' => [
                    'fileField' => 'https://www.llqhz.cn',
                ],
            ]
        ];
        return  array_merge( parent::actions(), $actions); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        \Yii::$app->response->format = Response::FORMAT_JSONP;
        return ['sss'];
    }

    public function beforeAction($action)
    {
        $request = Yii::$app->request;
        Yii::setAlias('@web',$request->getHostInfo().$request->getBaseUrl());
        return true;
    }

    public function afterAction($action,$result)
    {
        if ( \Yii::$app->response->format == Response::FORMAT_JSONP ) {
            \Yii::$app->response->format = Response::FORMAT_RAW;
            $request = \Yii::$app->request;
            return  $request->get('callback') . '('. Json::encode($result) . ')';
        } else {
            return $result;
        }
    }

    public function actionImgUpload()
    {
        $file = UploadedFile::getInstanceByName('image');
        if ( !$file ) {
            return ['code'=>0,'msg'=>'上传文件不存在'];
        }
        $path = 'uploads/images/'.date('Ymd/His/').$file->baseName.'.'.$file->extension;
        if (!file_exists(dirname($path))) {
            mkdir(dirname($path), 0777, true);
        }
        // 这个函数有毒 是该php安装本身的问题
        $file->saveAs($path,false);
        $url = Yii::getAlias('@web').'/'.$path;
        return ['code'=>1,'msg'=>'上传成功','url'=>$url];
    }

}